name: Build
run-name: Run by ${{ github.actor }}
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: List
        run: |
          ls ${{ github.workspace }}
      - run: echo "job status - ${{ job.status }}"
